namespace TallyConnector.Models.TallyPrime.V7.Masters;

[XmlType(AnonymousType = true)]
[XmlRoot("LEDGER")]
[GenerateITallyRequestableObect]
[GenerateMeta]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class Ledger :V6.Masters.Ledger
{
}

