using TallyConnector.Core.Models;

namespace TallyConnector.MigrationTests.Models;

public class BaseLedgerEntry 
{
    public int Amount { get; set; }
}

public class BaseVoucher : TallyXml
{
    [XmlElement(ElementName = "OLDLEDGERENTRIES.LIST", Type = typeof(BaseLedgerEntry))]
    public List<BaseLedgerEntry> LedgerEntries { get; set; } = new();
}

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class PolymorphicVoucher : BaseVoucher
{
    [XmlElement(ElementName = "ALLLEDGERENTRIES.LIST", Type = typeof(AllLedgerEntry))]
    [XmlElement(ElementName = "LEDGERENTRIES.LIST", Type = typeof(LedgerEntry))]
    public new List<BaseLedgerEntry> LedgerEntries { get; set; } = new();
}

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class AllLedgerEntry : BaseLedgerEntry, XmlSourceGenerator.Abstractions.IXmlStreamable
{
    [XmlIgnore]
    public int Id { get; set; }
    public string ExtraInfo { get; set; }
}

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class LedgerEntry : BaseLedgerEntry, XmlSourceGenerator.Abstractions.IXmlStreamable
{
    public int Priority { get; set; }
}
