using TallyConnector.Core.Models;
using SysXml = System.Xml.Serialization;

namespace TallyConnector.MigrationTests.Models;

/// <summary>
/// Simple test model for basic type serialization
/// Uses System.Xml.Serialization attributes for XmlSerializer
/// and XmlAutoGenerated for XmlSourceGenerator
/// </summary>
[SysXml.XmlRoot(ElementName = "TESTOBJECT")]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class SimpleTestObject : TallyXml
{
    [SysXml.XmlElement(ElementName = "NAME")]
    public string? Name { get; set; }

    [SysXml.XmlElement(ElementName = "ID")]
    public int Id { get; set; }

    [SysXml.XmlElement(ElementName = "AMOUNT")]
    public decimal Amount { get; set; }

    [SysXml.XmlElement(ElementName = "ISACTIVE")]
    public bool IsActive { get; set; }

    [SysXml.XmlElement(ElementName = "CREATEDON")]
    public DateTime CreatedOn { get; set; }

    [SysXml.XmlElement(ElementName = "OPTIONALVALUE")]
    public int? OptionalValue { get; set; }
}

/// <summary>
/// Test object with XML attributes
/// </summary>
[SysXml.XmlRoot(ElementName = "ATTRIBUTETEST")]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class AttributeTestObject : TallyXml
{
    [SysXml.XmlAttribute(AttributeName = "ID")]
    public int Id { get; set; }

    [SysXml.XmlAttribute(AttributeName = "TYPE")]
    public string? Type { get; set; }

    [SysXml.XmlElement(ElementName = "VALUE")]
    public string? Value { get; set; }
}

/// <summary>
/// Test object with collections
/// </summary>
[SysXml.XmlRoot(ElementName = "COLLECTIONTEST")]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class CollectionTestObject : TallyXml
{
    [SysXml.XmlElement(ElementName = "NAME")]
    public string? Name { get; set; }

    [SysXml.XmlArray(ElementName = "ITEMS.LIST")]
    [SysXml.XmlArrayItem(ElementName = "ITEM")]
    public List<string>? Items { get; set; }

    [SysXml.XmlArray(ElementName = "NUMBERS.LIST")]
    [SysXml.XmlArrayItem(ElementName = "NUMBER")]
    public List<int>? Numbers { get; set; }
}

/// <summary>
/// Nested test object
/// </summary>
[SysXml.XmlRoot(ElementName = "NESTEDITEM")]

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class NestedItem : TallyXml
{
    [SysXml.XmlElement(ElementName = "ITEMNAME")]
    
    public string? ItemName { get; set; }

    [SysXml.XmlElement(ElementName = "QUANTITY")]
    
    public decimal Quantity { get; set; }
}

/// <summary>
/// Test object with nested objects
/// </summary>
[SysXml.XmlRoot(ElementName = "NESTEDTEST")]

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class NestedTestObject : TallyXml
{
    [SysXml.XmlElement(ElementName = "NAME")]
    
    public string? Name { get; set; }

    [SysXml.XmlElement(ElementName = "NESTEDITEMS.LIST")]
    
    public List<NestedItem>? NestedItems { get; set; }
}

/// <summary>
/// Simplified Company model for testing
/// </summary>
[SysXml.XmlRoot(ElementName = "COMPANY")]

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class TestCompany : TallyXml
{
    [SysXml.XmlElement(ElementName = "NAME")]
    
    public string? Name { get; set; }

    [SysXml.XmlElement(ElementName = "GUID")]
    
    public string? GUID { get; set; }

    [SysXml.XmlElement(ElementName = "BOOKSFROM")]
    
    public DateTime BooksFrom { get; set; }

    [SysXml.XmlElement(ElementName = "STATENAME")]
    
    public string? State { get; set; }

    [SysXml.XmlElement(ElementName = "PINCODE")]
    
    public string? PinCode { get; set; }

    [SysXml.XmlElement(ElementName = "EMAIL")]
    
    public string? Email { get; set; }

    [SysXml.XmlElement(ElementName = "ISINVENTORYON")]
    
    public bool IsInventoryOn { get; set; }

    [SysXml.XmlElement(ElementName = "ISGSTON")]
    
    public bool IsGSTOn { get; set; }
}

/// <summary>
/// Simplified Ledger Entry for testing
/// </summary>
[SysXml.XmlRoot(ElementName = "LEDGERENTRY")]

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class TestLedgerEntry : TallyXml
{
    [SysXml.XmlElement(ElementName = "LEDGERNAME")]
    
    public string? LedgerName { get; set; }

    [SysXml.XmlElement(ElementName = "ISDEEMEDPOSITIVE")]
    
    public bool IsDeemedPositive { get; set; }

    [SysXml.XmlElement(ElementName = "AMOUNT")]
    
    public decimal Amount { get; set; }
}

/// <summary>
/// Simplified Voucher model for testing
/// </summary>
[SysXml.XmlRoot(ElementName = "VOUCHER")]

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class TestVoucher : TallyXml
{
    [SysXml.XmlElement(ElementName = "DATE")]
    
    public DateTime Date { get; set; }

    [SysXml.XmlElement(ElementName = "VOUCHERTYPENAME")]
    
    public string? VoucherType { get; set; }

    [SysXml.XmlElement(ElementName = "VOUCHERNUMBER")]
    
    public string? VoucherNumber { get; set; }

    [SysXml.XmlElement(ElementName = "PARTYNAME")]
    
    public string? PartyName { get; set; }

    [SysXml.XmlElement(ElementName = "NARRATION")]
    
    public string? Narration { get; set; }

    [SysXml.XmlElement(ElementName = "LEDGERENTRIES.LIST")]
    
    public List<TestLedgerEntry>? LedgerEntries { get; set; }
}

/// <summary>
/// Base class for polymorphic test
/// </summary>
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
[SysXml.XmlInclude(typeof(DerivedItemA))]
[SysXml.XmlInclude(typeof(DerivedItemB))]
public partial class BaseItem : TallyXml
{
    [SysXml.XmlElement(ElementName = "NAME")]
    public string? Name { get; set; }
}

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class DerivedItemA : BaseItem
{
    [SysXml.XmlElement(ElementName = "PROP_A")]
    public string? PropertyA { get; set; }
}

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class DerivedItemB : BaseItem
{
    [SysXml.XmlElement(ElementName = "PROP_B")]
    public string? PropertyB { get; set; }
}

/// <summary>
/// Test object with polymorphic list using XmlElement Type
/// </summary>
[SysXml.XmlRoot(ElementName = "POLYMORPHICTEST")]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class PolymorphicListTestObject : TallyXml
{
    [SysXml.XmlElement(ElementName = "ITEM_A", Type = typeof(DerivedItemA))]
    [SysXml.XmlElement(ElementName = "ITEM_B", Type = typeof(DerivedItemB))]
    public List<BaseItem>? Items { get; set; }
}

/// <summary>
/// Plain object for testing AttributeOverrides
/// </summary>
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class PlainListObject : TallyXml
{
    public List<BaseItem>? Items { get; set; }
}
