namespace TallyConnector.Core.Models.TallyComplexObjects;
[TDLCollection(ExplodeCondition = "NOT $$IsEmpty:{0}")]
[GenerateMeta]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class TallyQuantityField : ITallyComplexObject, IBaseObject
{
    public TallyQuantityField()
    {
    }

    public TallyQuantityField(decimal quantity, string unit)
    {
        Quantity = quantity;
        Unit = unit;
    }

    [TDLField(TallyType = "Quantity : UnitSymbol", Set = "{0}")]
    [XmlElement(ElementName = "UNIT")]
    public string Unit { get; set; } = null!;

    [TDLField(TallyType = "Number", Format = "TailUnits", Set ="{0}")]
    [XmlElement(ElementName = "QUANTITY")]
    [Column(TypeName = "decimal(20,4)")]
    public decimal Quantity { get; set; }


    public override string ToString()
    {
        return $" {Quantity} {Unit}";
    }
}
