global using NUnit.Framework;
global using System.Text;
global using System.Text.Json;
global using System.Xml;
global using System.Xml.Serialization;
global using TallyConnector.Core.Converters.JSONConverters;
global using TallyConnector.Core.Converters.XMLConverterHelpers;
global using TallyConnector.Services;
global using TCM = TallyConnector.Core.Models;
global using TCMA = TallyConnector.Core.Models.Masters;
global using TCMI = TallyConnector.Core.Models.Masters.Inventory;
global using TC = TallyConnector.Services;
