namespace TallyConnector.Models.TallyPrime.V7;

[XmlRoot(ElementName = "VOUCHER")]
[XmlType(AnonymousType = true)]
[GenerateITallyRequestableObect]
[GenerateMeta]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class Voucher :V6.Voucher
{
    //IBaseTallyObject ToDTO()
    //{
    //    return this;
    //}


}

