namespace TallyConnector.Models.Common;


[XmlRoot(ElementName = "LEDMULTIADDRESSLIST")]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class MultiAddress
{

    public MultiAddress()
    {
        ExciseJurisdictions = [];
        AddressName = string.Empty;
    }

    [XmlElement(ElementName = "MAILINGNAME")]
    public string AddressName { get; set; }

    [XmlArray(ElementName = "ADDRESS.LIST")]
    [XmlArrayItem(ElementName = "ADDRESS")]
    [TDLCollection(CollectionName = "ADDRESS")]
    public List<string> AddressLines {  get; set; }

    [XmlElement(ElementName = "COUNTRYNAME")]
    [MaxLength(5)]
    public string? Country { get; set; }

    [XmlElement(ElementName = "LEDSTATENAME")]
    [MaxLength(MaxNameLength)]
    public string? State { get; set; }

    [XmlElement(ElementName = "PINCODE")]
    [MaxLength(15)]
    public string? PinCode { get; set; }

    [XmlElement(ElementName = "CONTACTPERSON")]
    [MaxLength(20)]
    public string? ContactPerson { get; set; }

    [XmlElement(ElementName = "MOBILENUMBER")]
    [MaxLength(20)]
    public string? MobileNo { get; set; }

    [XmlElement(ElementName = "PHONENUMBER")]
    [MaxLength(20)]
    public string? PhoneNumber { get; set; }

    [XmlElement(ElementName = "FAXNUMBER")]
    [MaxLength(20)]
    public string? FaxNumber { get; set; }

    [XmlElement(ElementName = "EMAIL")]
    [MaxLength(60)]
    public string? Email { get; set; }



    [XmlElement(ElementName = "INCOMETAXNUMBER")]
    [MaxLength(12)]
    public string? PANNumber { get; set; }

    [XmlElement(ElementName = "VATTINNUMBER")]
    [MaxLength(20)]
    public string? VATNumber { get; set; }

    [XmlElement(ElementName = "INTERSTATESTNUMBER")]
    [MaxLength(20)]
    public string? CSTNumber { get; set; }

    [XmlElement(ElementName = "EXCISENATUREOFPURCHASE")]
    [MaxLength(10)]
    public ExciseNatureOfPurchase ExciseNatureOfPurchase { get; set; }

    [XmlElement(ElementName = "EXCISEREGNO")]
    [MaxLength(20)]
    public string? ExciseRegistrationNo { get; set; }

    [XmlElement(ElementName = "EXCISEIMPORTSREGISTARTIONNO")]
    [MaxLength(20)]
    public string? ExciseImportRegistrationNo { get; set; }

    [XmlElement(ElementName = "IMPORTEREXPORTERCODE")]
    [MaxLength(20)]
    public string? ImportExportCode { get; set; }

    [XmlElement(ElementName = "GSTREGISTRATIONTYPE")]
    public GSTRegistrationType GSTDealerType { get; set; }

    [XmlElement(ElementName = "ISOTHTERRITORYASSESSEE")]
    public bool? IsOtherTerritoryAssessee { get; set; }

    [XmlElement(ElementName = "PARTYGSTIN")]
    [MaxLength(17)]
    public string? GSTIN { get; set; }

    [XmlElement(ElementName = "EXCISEJURISDICTIONDETAILS.LIST")]
    [TDLCollection(CollectionName = "EXCISEJURISDICTIONDETAILS", ExplodeCondition = "$$NUMITEMS:EXCISEJURISDICTIONDETAILS>0")]
    public List<ExciseJurisdiction>? ExciseJurisdictions { get; set; }
    

}
[XmlRoot(ElementName = "EXCISEJURISDICTIONDETAILS.LIST")]
public partial class ExciseJurisdiction
{
    [XmlElement(ElementName = "APPLICABLEFROM")]
    public DateTime? ApplicableFrom { get; set; }

    [XmlElement(ElementName = "RANGE")]
    [MaxLength(20)]
    public string? Range { get; set; }

    [XmlElement(ElementName = "DIVISION")]
    [MaxLength(20)]
    public string? Division { get; set; }

    [XmlElement(ElementName = "COMMISSIONERATE")]
    [MaxLength(20)]
    public string? Commissionerate { get; set; }

  
}

