namespace TallyConnector.Models.Common;

[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class ContactDetail
{
    [XmlElement("COUNTRYISDCODE")]
    public string CountryISOCode { get; set; }

    [XmlElement("ISDEFAULTWHATSAPPNUM")]
    public bool IsDefaultWhatsAppNumber { get; set; }

    [XmlElement("NAME")]
    public string Name { get; set; }

    [XmlElement("PHONENUMBER")]
    public string PhoneNumber { get; set; }
}