global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Xml;
global using System.Linq;
global using System.Xml.Serialization;
global using TallyConnector.Core.Attributes;
global using TallyConnector.Core.Models.Interfaces;
global using TallyConnector.Core.Models.Request;
global using TallyConnector.Core.Attributes.SourceGenerator;
global using TallyConnector.Core.Models.TallyComplexObjects;
global using TallyConnector.Core.Models.TallyComplexObjects.Meta;
global using TallyConnector.Models.Common.Meta;
global using static TallyConnector.Core.Constants;
global using  TallyConnector.Abstractions.Attributes;
