namespace TallyConnector.Models.TallyPrime.V3.Masters;

[XmlType(AnonymousType = true)]
[XmlRoot("GROUP")]
[GenerateITallyRequestableObect]
[GenerateMeta]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial  class Group : Base.Masters.Group
{

}
