namespace TallyConnector.Models.TallyPrime.V3.Masters;

[XmlType(AnonymousType = true)]
[XmlRoot("LEDGER")]
[GenerateITallyRequestableObect]
[GenerateMeta]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class Ledger : Base.Masters.Ledger
{
}
