using XmlEnumAttribute = XmlSourceGenerator.Abstractions.XmlEnumAttribute;
using XmlIncludeAttribute = XmlSourceGenerator.Abstractions.XmlIncludeAttribute;

namespace TallyConnector.MigrationTests.Tests;

[TestFixture]
public partial class PortedFeaturesTests
{
    #region XmlEnum Tests

    public enum Status
    {
        [XmlEnum("active")]
        Active,
        [XmlEnum("inactive")]
        Inactive,
        [XmlEnum("pending")]
        Pending
    }

    [XmlSourceGenerator.Abstractions.XmlAutoGenerated]
    public partial class UserAccount : TallyConnector.Core.Models.TallyXml
    {
        public string Username { get; set; }
        public Status AccountStatus { get; set; }
    }

    [Test]
    public void XmlEnum_SerializesWithCustomValue_Active()
    {
        var account = new UserAccount 
        { 
            Username = "john",
            AccountStatus = Status.Active 
        };
        
        var xml = account.WriteToXml();
        
        Assert.That(xml.Element("AccountStatus")?.Value, Is.EqualTo("active"));
    }

    [Test]
    public void XmlEnum_SerializesWithCustomValue_Inactive()
    {
        var account = new UserAccount 
        { 
            Username = "jane",
            AccountStatus = Status.Inactive
        };
        
        var xml = account.WriteToXml();
        
        Assert.That(xml.Element("AccountStatus")?.Value, Is.EqualTo("inactive"));
    }

    [Test]
    public void XmlEnum_DeserializesFromCustomValue_Active()
    {
        var xml = XElement.Parse(@"
            <UserAccount>
                <Username>john</Username>
                <AccountStatus>active</AccountStatus>
            </UserAccount>");

        var account = new UserAccount();
        account.ReadFromXml(xml);

        Assert.That(account.AccountStatus, Is.EqualTo(Status.Active));
    }

    [Test]
    public void XmlEnum_DeserializesFromCustomValue_Pending()
    {
        var xml = XElement.Parse(@"
            <UserAccount>
                <Username>bob</Username>
                <AccountStatus>pending</AccountStatus>
            </UserAccount>");

        var account = new UserAccount();
        account.ReadFromXml(xml);

        Assert.That(account.AccountStatus, Is.EqualTo(Status.Pending));
    }

    #endregion

    #region XmlInclude Tests

    [XmlInclude(typeof(Dog))]
    [XmlInclude(typeof(Cat))]
    [XmlSourceGenerator.Abstractions.XmlAutoGenerated]
    public partial class Animal : TallyConnector.Core.Models.TallyXml
    {
        public string Name { get; set; }
    }

    [XmlSourceGenerator.Abstractions.XmlAutoGenerated]
    public partial class Dog : Animal
    {
        public bool CanBark { get; set; }
    }

    [XmlSourceGenerator.Abstractions.XmlAutoGenerated]
    public partial class Cat : Animal
    {
        public int LivesRemaining { get; set; }
    }

    [Test]
    public void XmlInclude_SerializesDerivedType_Dog()
    {
        var dog = new Dog { Name = "Buddy", CanBark = true };
        var xml = dog.WriteToXml();

        Assert.That(xml.Name.LocalName, Is.EqualTo("Dog"));
        Assert.That(xml.Element("Name")?.Value, Is.EqualTo("Buddy"));
        Assert.That(xml.Element("CanBark")?.Value, Is.EqualTo("true"));
    }

    [Test]
    public void XmlInclude_SerializesDerivedType_Cat()
    {
        var cat = new Cat { Name = "Whiskers", LivesRemaining = 9 };
        var xml = cat.WriteToXml();

        Assert.That(xml.Name.LocalName, Is.EqualTo("Cat"));
        Assert.That(xml.Element("Name")?.Value, Is.EqualTo("Whiskers"));
        Assert.That(xml.Element("LivesRemaining")?.Value, Is.EqualTo("9"));
    }

    [Test]
    public void XmlInclude_DeserializesDerivedType_Dog()
    {
        var xml = XElement.Parse(@"
            <Dog>
                <Name>Buddy</Name>
                <CanBark>true</CanBark>
            </Dog>");

        var dog = new Dog();
        dog.ReadFromXml(xml);

        Assert.That(dog.Name, Is.EqualTo("Buddy"));
        Assert.That(dog.CanBark, Is.True);
    }

    [Test]
    public void XmlInclude_DeserializesDerivedType_Cat()
    {
        var xml = XElement.Parse(@"
            <Cat>
                <Name>Whiskers</Name>
                <LivesRemaining>9</LivesRemaining>
            </Cat>");

        var cat = new Cat();
        cat.ReadFromXml(xml);

        Assert.That(cat.Name, Is.EqualTo("Whiskers"));
        Assert.That(cat.LivesRemaining, Is.EqualTo(9));
    }

    #endregion
}
