namespace TallyConnector.Models.TallyPrime.V3;

[XmlRoot(ElementName = "VOUCHER")]
[XmlType(AnonymousType = true)]
[GenerateITallyRequestableObect]
[GenerateMeta]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class Voucher : TallyConnector.Models.Base.Voucher
{
    
}

