using TallyConnector.Models.Common;

namespace TallyConnector.Models.Base;
[XmlRoot(ElementName = "VOUCHER")]
[XmlType(AnonymousType = true)]
[TDLCollection(Type = "Voucher")]
[MaptoDTO<BaseVoucherDTO>]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class BaseVoucher : TallyObject, IBaseVoucherObject
{
    [IgnoreForCreateDTO]
    [XmlElement(ElementName = "ALTEREDON")]
    public DateTime? AlteredOn { get; set; }
}
public class BaseVoucherDTO : TallyObjectDTO
{
    [XmlAttribute("TAGNAME")]
    public string? TagName { get; set; }

    [XmlAttribute("TAGVALUE")]
    public string? TagValue { get; set; }

    [XmlAttribute("DATE")]
    public string DateAttr { get; set; }

    [XmlAttribute("VCHTYPE")]
    public string VchTypeAttr { get; set; }

    public void SetMasterIdasTagValue(ulong MasterId)
    {
        TagName = nameof(BaseVoucher.MasterId);
        TagValue = MasterId.ToString();
    }
    public void SetVoucherNumberasTagValue(string vchType, string VchNo)
    {
        TagName = nameof(Voucher.VoucherNumber);
        TagValue = VchNo;
        VchTypeAttr = vchType;
    }

}
[XmlRoot(ElementName = "VOUCHER")]
[XmlType(AnonymousType = true)]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class Voucher : BaseVoucher,IVoucherObject
{
    [XmlElement(ElementName = "DATE")]
    public DateTime Date { get; set; }

    [XmlElement(ElementName = "EFFECTIVEDATE")]
    public DateTime? EffectiveDate { get; set; }

    [XmlElement(ElementName = "REFERENCEDATE")]
    public DateTime? ReferenceDate { get; set; }

    [XmlElement(ElementName = "REFERENCE")]
    [TDLField(FetchText = "REFERENCE", ExcludeInFetch = true)]
    public string? Reference { get; set; }

    [XmlElement(ElementName = "VOUCHERTYPENAME")]
    public string VoucherType { get; set; }

    [XmlElement(ElementName = "PERSISTEDVIEW")]
    public VoucherViewType View { get; set; }

    [XmlElement(ElementName = "VCHGSTCLASS")]
    public string? VoucherGSTClass { get; set; }

    [XmlElement(ElementName = "ISCOSTCENTRE")]
    public bool? IsCostCentre { get; set; }

    [XmlElement(ElementName = "COSTCENTRENAME")]
    public string? CostCentreName { get; set; }

    [XmlElement(ElementName = "VCHENTRYMODE")]
    public string? VoucherEntryMode { get; set; }

    [XmlElement(ElementName = "ISINVOICE")]
    public bool IsInvoice { get; set; }

    [XmlElement(ElementName = "VOUCHERNUMBER")]
    public string? VoucherNumber { get; set; }

    [XmlElement(ElementName = "ISOPTIONAL")]
    public bool IsOptional { get; set; }

    [XmlElement(ElementName = "NARRATION")]
    public string? Narration { get; set; }

    [XmlElement(ElementName = "PRICELEVEL")]
    public string? PriceLevel { get; set; }

    //E-Invoice Details
    //[TallyCategory(Constants.Voucher.Category.EInvoiceDetails)]
    [XmlElement(ElementName = "BILLTOPLACE")]
    public string? BillToPlace { get; set; }

    //[TallyCategory(Constants.Voucher.Category.EInvoiceDetails)]
    [XmlElement(ElementName = "IRN")]
    public string? IRN { get; set; }

    // [TallyCategory(Constants.Voucher.Category.EInvoiceDetails)]
    [XmlElement(ElementName = "IRNACKNO")]
    public string? IRNAckNo { get; set; }

    //[TallyCategory(Constants.Voucher.Category.EInvoiceDetails)]
    [XmlElement(ElementName = "IRNACKDATE")]
    public string? IRNAckDate { get; set; }





    [TallyCategory("DispatchDetails")]
    [XmlElement(ElementName = "DISPATCHFROMNAME")]
    public string? DispatchFromName { get; set; }

    [TallyCategory("DispatchDetails")]
    [XmlElement(ElementName = "DISPATCHFROMSTATENAME")]
    public string? DispatchFromStateName { get; set; }

    [TallyCategory("DispatchDetails")]
    [XmlElement(ElementName = "DISPATCHFROMPINCODE")]
    public string? DispatchFromPinCode { get; set; }

    [TallyCategory("DispatchDetails")]
    [XmlElement(ElementName = "DISPATCHFROMPLACE")]
    public string? DispatchFromPlace { get; set; }

    [TallyCategory("ShippingDetails")]
    [TDLCollection(CollectionName = "INVOICEDELNOTES", ExplodeCondition = $"$$NumItems:INVOICEDELNOTES > 0")]
    [XmlElement(ElementName = "DELIVERYNOTES")]
    public DeliveryNotes? DeliveryNotes { get; set; }

    [TallyCategory("ShippingDetails")]
    [XmlElement(ElementName = "BASICSHIPDOCUMENTNO")]
    public string? DispatchDocNo { get; set; }
    [TallyCategory("ShippingDetails")]
    [XmlElement(ElementName = "BASICSHIPPEDBY")]
    public string? BasicShippedBy { get; set; }
    [TallyCategory("ShippingDetails")]
    [XmlElement(ElementName = "BASICFINALDESTINATION")]
    public string? Destination { get; set; }

    [TallyCategory("ShippingDetails")]
    [XmlElement(ElementName = "EICHECKPOST")]
    public string? CarrierName { get; set; }

    [TallyCategory("ShippingDetails")]
    [XmlElement(ElementName = "BILLOFLADINGNO")]
    public string? BillofLandingNo { get; set; }

    [TallyCategory("ShippingDetails")]
    [XmlElement(ElementName = "BILLOFLADINGDATE")]
    public string? BillofLandingDate { get; set; }


    //Export Shipping Details
    [TallyCategory("ExportShippingDetails")]
    [XmlElement(ElementName = "BASICPLACEOFRECEIPT")]
    public string? PlaceOfReceipt { get; set; }

    /// <summary>
    /// Vehicle or Ship or Flight Number
    /// </summary>
    [TallyCategory("ExportShippingDetails")]
    [XmlElement(ElementName = "BASICSHIPVESSELNO")]
    public string? ShipOrFlightNo { get; set; }

    [TallyCategory("ExportShippingDetails")]
    [XmlElement(ElementName = "BASICPORTOFLOADING")]
    public string? LandingPort { get; set; }

    [TallyCategory("ExportShippingDetails")]
    [XmlElement(ElementName = "BASICPORTOFDISCHARGE")]
    public string? DischargePort { get; set; }

    [TallyCategory("ExportShippingDetails")]
    [XmlElement(ElementName = "BASICDESTINATIONCOUNTRY")]
    public string? DestinationCountry { get; set; }

    [TallyCategory("ExportShippingDetails")]
    [XmlElement(ElementName = "SHIPPINGBILLNO")]
    public string? ShippingBillNo { get; set; }

    [TallyCategory("ExportShippingDetails")]
    [XmlElement(ElementName = "SHIPPINGBILLDATE")]
    public string? ShippingBillDate { get; set; }

    [TallyCategory("ExportShippingDetails")]
    [XmlElement(ElementName = "PORTCODE")]
    public string? PortCode { get; set; }

    //OrderDetails
    [TallyCategory("OrderDetails")]
    [XmlElement(ElementName = "BASICDUEDATEOFPYMT")]
    public string? BasicDueDateofPayment { get; set; }

    [TallyCategory("OrderDetails")]
    [XmlElement(ElementName = "BASICORDERREF")]
    public string? OrderReference { get; set; }



    //Party Details
    [TallyCategory("PartyDetails")]
    [XmlElement(ElementName = "PARTYNAME")]
    public string? PartyName { get; set; }

    [XmlElement(ElementName = "VOUCHERNUMBERSERIES")]
    public string? VoucherNumberSeries { get; set; }

    [TallyCategory("PartyDetails")]
    [XmlElement(ElementName = "PARTYMAILINGNAME")]
    public string? PartyMailingName { get; set; }

    [TallyCategory("PartyDetails")]
    [XmlElement(ElementName = "STATENAME")]
    public string? State { get; set; }

    [TallyCategory("PartyDetails")]
    [XmlElement(ElementName = "COUNTRYOFRESIDENCE")]
    public string? Country { get; set; }

    [XmlElement(ElementName = "GSTREGISTRATION")]
    public string? GSTRegistration { get; set; }

    [TallyCategory("PartyDetails")]
    [XmlElement(ElementName = "GSTREGISTRATIONTYPE")]
    public string? RegistrationType { get; set; }

    [TallyCategory("PartyDetails")]
    [XmlElement(ElementName = "PARTYGSTIN")]
    public string? PartyGSTIN { get; set; }

    [TallyCategory("PartyDetails")]
    [XmlElement(ElementName = "PLACEOFSUPPLY")]
    public string? PlaceOfSupply { get; set; }

    [TallyCategory("PartyDetails")]
    [XmlElement(ElementName = "PARTYPINCODE")]
    public string? PINCode { get; set; }

    //Consignee Details
    [TallyCategory("ConsigneeDetails")]
    [XmlElement(ElementName = "BASICBUYERNAME")]
    public string? ConsigneeName { get; set; }

    [TallyCategory("ConsigneeDetails")]
    [XmlElement(ElementName = "CONSIGNEEMAILINGNAME")]
    public string? ConsigneeMailingName { get; set; }

    [TallyCategory("ConsigneeDetails")]
    [XmlElement(ElementName = "CONSIGNEESTATENAME")]
    public string? ConsigneeState { get; set; }

    [TallyCategory("ConsigneeDetails")]
    [XmlElement(ElementName = "CONSIGNEECOUNTRYNAME")]
    public string? ConsigneeCountry { get; set; }

    [TallyCategory("ConsigneeDetails")]
    [XmlElement(ElementName = "CONSIGNEEGSTIN")]
    public string? ConsigneeGSTIN { get; set; }

    [TallyCategory("ConsigneeDetails")]
    [XmlElement(ElementName = "CONSIGNEEPINCODE")]
    public string? ConsigneePinCode { get; set; }

    [XmlArray(ElementName = "ADDRESS.LIST")]
    [XmlArrayItem(ElementName = "ADDRESS")]
    [TDLCollection(CollectionName = "Address", ExplodeCondition = "$$NumItems:ADDRESS<1")]
    public List<string>? Address { get; set; }

    [XmlArray(ElementName = "BASICBUYERADDRESS.LIST")]
    [XmlArrayItem(ElementName = "BASICBUYERADDRESS")]
    [TDLCollection(CollectionName = "Address", ExplodeCondition = "$$NumItems:BASICBUYERADDRESS<1")]

    public List<string>? BuyerAddress { get; set; }

    [XmlElement(ElementName = "ISCANCELLED")]
    public bool IsCancelled { get; set; } =false;

    //EWAY Details
    [XmlElement(ElementName = "OVRDNEWAYBILLAPPLICABILITY")]
    public bool? OverrideEWayBillApplicability { get; set; }

    [XmlElement(ElementName = "EWAYBILLDETAILS.LIST")]
    [TDLCollection(CollectionName = "EWAYBILLDETAILS", ExplodeCondition = "$$NUMITEMS:EWAYBILLDETAILS>0")]
    public List<EwayBillDetails>? EwayBillDetails { get; set; }

    [XmlElement(ElementName = "ALLLEDGERENTRIES.LIST", Type = typeof(AllLedgerEntry))]
    [XmlElement(ElementName = "LEDGERENTRIES.LIST", Type = typeof(LedgerEntry))]
    public List<AllLedgerEntry> LedgerEntries { get; set; } = [];

    [XmlElement(ElementName = "ALLINVENTORYENTRIES.LIST", Type = typeof(AllInventoryEntries))]
    [XmlElement(ElementName = "INVENTORYENTRIES.LIST", Type = typeof(InventoryEntries))]
    public List<AllInventoryEntries> InventoryAllocations { get; set; } = [];

    public override string ToString()
    {
        return $"Voucher - {VoucherType}_{VoucherNumber}_{Date.ToShortDateString()}";
    }
}

[XmlType(AnonymousType = true)]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class BaseInventoryEntry
{
    [XmlArray("BASICUSERDESCRIPTION.LIST")]
    [XmlArrayItem(ElementName = "BASICUSERDESCRIPTION")]
    [TDLCollection(CollectionName = "BASICUSERDESCRIPTION")]
    public List<string> UserDescriptions { get; set; }

    [XmlElement(ElementName = "INDEXNUMBER")]
    public int IndexNumber { get; set; }

    [XmlElement(ElementName = "STOCKITEMNAME")]
    public string? StockItemName { get; set; }


    [XmlElement(ElementName = "BOMNAME")]
    public string? BOMName { get; set; }

    [XmlElement(ElementName = "ISSCRAP")]
    public bool? IsScrap { get; set; }

    [XmlElement(ElementName = "DISCOUNT")]
    public decimal? Discount { get; set; }


    [XmlElement(ElementName = "ISDEEMEDPOSITIVE")]
    public bool IsDeemedPositive { get; set; }

    [XmlElement(ElementName = "RATE")]
    public TallyRateField? Rate { get; set; }

    [XmlElement(ElementName = "ACTUALQTY")]
    public TallyQuantityField? ActualQuantity { get; set; }

    [XmlElement(ElementName = "BILLEDQTY")]
    public TallyQuantityField? BilledQuantity { get; set; }

    [XmlElement(ElementName = "AMOUNT")]
    public TallyAmountField? Amount { get; set; }


    [XmlElement(ElementName = "BATCHALLOCATIONS.LIST")]
    [TDLCollection(CollectionName = "BATCHALLOCATIONS")]
    public List<BatchAllocation>? BatchAllocations { get; set; }
}

[XmlRoot(ElementName = "ALLINVENTORYENTRIES.LIST")]
[XmlType(AnonymousType = true)]
[TDLCollection(CollectionName = "ALLINVENTORYENTRIES", ExplodeCondition = $"$PERSISTEDVIEW =$$SysName:{Core.Constants.Voucher.ViewType.InvoiceVoucherView}")]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class AllInventoryEntries : BaseInventoryEntry
{
    [XmlElement(ElementName = "ACCOUNTINGALLOCATIONS.LIST")]
    [TDLCollection(CollectionName = "ACCOUNTINGALLOCATIONS")]
    public List<BaseLedgerEntry>? Ledgers { get; set; } = [];
}

[XmlRoot(ElementName = "INVENTORYENTRIES.LIST")]
[XmlType(AnonymousType = true)]
[TDLCollection(CollectionName = "INVENTORYENTRIES", ExplodeCondition = $"$PERSISTEDVIEW =$$SysName:{Core.Constants.Voucher.ViewType.MfgJournalVoucherView}")]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class InventoryEntries : AllInventoryEntries
{
}
[XmlType(AnonymousType = true)]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class BaseLedgerEntry
{
    public BaseLedgerEntry()
    {
    }


    [XmlElement(ElementName = "INDEXNUMBER")]
    public int IndexNumber { get; set; }

    [XmlElement(ElementName = "LEDGERNAME")]
    public string LedgerName { get; set; }

    [XmlElement(ElementName = "LEDGERTAXTYPE")]
    public string? LedgerTaxType { get; set; }

    [XmlElement(ElementName = "VCHLEDGERTYPE")]
    public string? LedgerType { get; set; }

    [XmlElement(ElementName = "ISDEEMEDPOSITIVE")]
    public bool IsDeemedPositive { get; set; }

    [XmlElement(ElementName = "AMOUNT")]
    public TallyAmountField Amount { get; set; }
}
[XmlRoot(ElementName = "ALLLEDGERENTRIES.LIST")]
[XmlType(AnonymousType = true)]
[TDLCollection(CollectionName = "ALLLEDGERENTRIES", ExplodeCondition = $"$PERSISTEDVIEW =$$SysName:{TallyConnector.Core.Constants.Voucher.ViewType.AccountingVoucherView}")]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class AllLedgerEntry : BaseLedgerEntry
{
    [XmlElement(ElementName = "ADDLALLOCTYPE")]
    public AdAllocType AdAllocType { get; set; }

    [XmlElement(ElementName = "ISPARTYLEDGER")]
    public bool IsPartyLedger { get; set; }

    [XmlElement(ElementName = "SWIFTCODE")]
    public string? SWIFTCode { get; set; }

    [XmlElement(ElementName = "BILLALLOCATIONS.LIST")]
    [TDLCollection(CollectionName = "BILLALLOCATIONS", ExplodeCondition = $"$$NUMITEMS:BILLALLOCATIONS>0")]
    public List<BillAllocations>? BillAllocations { get; set; } = [];

    [XmlElement(ElementName = "INVENTORYALLOCATIONS.LIST")]
    [TDLCollection(CollectionName = "INVENTORYALLOCATIONS", ExplodeCondition = $"$$NUMITEMS:INVENTORYALLOCATIONS>0")]
    public List<BaseInventoryEntry>? InventoryAllocations { get; set; } = [];
}

[XmlRoot(ElementName = "BILLALLOCATIONS.LIST")]
[XmlType(AnonymousType = true)]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class BillAllocations
{
    [XmlElement(ElementName = "BILLTYPE")]
    public BillRefType? BillType { get; set; }

    [XmlElement(ElementName = "NAME")]
    public string? Name { get; set; }


    [XmlElement(ElementName = "BILLCREDITPERIOD")]
    public DueDate? BillCreditPeriod { get; set; }

    [XmlElement(ElementName = "AMOUNT")]
    public TallyAmountField? Amount { get; set; }
}
public enum BillRefType
{
    [EnumXMLChoice(Choice = "New Ref")]
    NewRef,
    [EnumXMLChoice(Choice = "On Account")]
    OnAccount,
    [EnumXMLChoice(Choice = "Agst Ref")]
    AgstRef,
    [EnumXMLChoice(Choice = "Advance")]
    Advance

}

[XmlRoot(ElementName = "LEDGERENTRIES.LIST")]
[XmlType(AnonymousType = true)]
[TDLCollection(CollectionName = "LEDGERENTRIES", ExplodeCondition = $"$PERSISTEDVIEW =$$SysName:{Core.Constants.Voucher.ViewType.InvoiceVoucherView}")]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class LedgerEntry : AllLedgerEntry
{
    public string? LedgerEntryProp { get; set; }

}
[XmlRoot(ElementName = "INVOICEDELNOTES.LIST")]
[XmlType(AnonymousType = true)]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class DeliveryNotes
{
    [XmlElement(ElementName = "BASICSHIPPINGDATE")]
    public DateTime? ShippingDate { get; set; }

    [XmlElement(ElementName = "BASICSHIPDELIVERYNOTE")]
    public string DeliveryNote { get; set; }
}
/// <summary>
/// <para>Voucher ViewTypes avavailable in Tally</para>
/// <para>TDL Reference -  src\voucher\vchreport.tdl
/// Search using "Set						: SVViewName"</para>
/// </summary>
public enum VoucherViewType
{
    [EnumXMLChoice(Choice = "")]
    None = 0,
    [EnumXMLChoice(Choice = "Accounting Voucher View")]
    AccountingVoucherView = 1,

    [EnumXMLChoice(Choice = "Invoice Voucher View")]
    InvoiceVoucherView = 2,

    [EnumXMLChoice(Choice = "PaySlip Voucher View")]
    PaySlipVoucherView = 3,

    [EnumXMLChoice(Choice = "Multi Consumption Voucher View")]
    MultiConsumptionVoucherView = 4,

    [EnumXMLChoice(Choice = "Consumption Voucher View")]
    ConsumptionVoucherView = 5,
}


[XmlRoot(ElementName = "BATCHALLOCATIONS.LIST")]
[XmlType(AnonymousType = true)]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class BatchAllocation
{
    [XmlElement(ElementName = "MFDON")]
    public DateTime? ManufacturedOn { get; set; }

    [XmlElement(ElementName = "TRACKINGNUMBER")]
    public string? TrackingNo { get; set; }

    [XmlElement(ElementName = "ORDERNO")]
    public string? OrderNo { get; set; }

    [XmlElement(ElementName = "GODOWNNAME")]
    public string? GodownName { get; set; }


    [XmlElement(ElementName = "BATCHNAME")]
    public string? BatchName { get; set; }

    [XmlElement(ElementName = "ORDERDUEDATE")]
    public DueDate? OrderDueDate { get; set; }

    [XmlElement(ElementName = "EXPIRYPERIOD")]
    public DueDate? ExpiryPeriod { get; set; }

    [XmlElement(ElementName = "AMOUNT")]
    public TallyAmountField? Amount { get; set; }

    [XmlElement(ElementName = "ACTUALQTY")]
    public TallyQuantityField? ActualQuantity { get; set; }

    [XmlElement(ElementName = "BILLEDQTY")]
    public TallyQuantityField? BilledQuantity { get; set; }
}
[XmlRoot(ElementName = "EWAYBILLDETAILS.LIST")]
[XmlType(AnonymousType = true)]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class EwayBillDetails
{
    [XmlElement(ElementName = "BILLNUMBER")]
    public string? BillNumber { get; set; }

    [XmlElement(ElementName = "BILLDATE")]
    public DateTime? BillDate { get; set; }

    [XmlElement(ElementName = "VALIDUPTO")]
    public DateTime? ValidUpto { get; set; }
    [XmlElement(ElementName = "DOCUMENTTYPE")]
    public string DocumentType { get; set; }


    [XmlElement(ElementName = "SUBTYPE")]
    public string? SubType { get; set; }
}