namespace TallyConnector.Models.TallyPrime.V6.Masters.Inventory;
[XmlRoot(ElementName = "STOCKITEM")]
[XmlType(AnonymousType = true)]
[GenerateITallyRequestableObect]
[GenerateMeta]
[XmlSourceGenerator.Abstractions.XmlAutoGenerated]
public partial class StockItem : Base.Masters.Inventory.StockItem
{
}
